export const BASKETBALL = "Basketball"
export const TENNIS = "Tennis"
export const SOCCER = "Soccer"
export const FRISBEE = "Frisbee"
export const VOLLEYBALL = "Volleyball"
export const BIKING = "Biking"
export const RUNNING = "Running"